; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mmix -verify-machineinstrs < %s | FileCheck %s

; Register-immediate instructions

define i64 @add(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: add:
; CHECK:       % %bb.0:
; CHECK-NEXT:    add $231,$231,$232
; CHECK-NEXT:    pop 0x0,0x0
  %1 = add i64 %a, %b
  ret i64 %1
}

define i64 @addi(i64 %a) nounwind {
; CHECK-LABEL: addi:
; CHECK:       % %bb.0:
; CHECK-NEXT:    add $231,$231,0x1
; CHECK-NEXT:    pop 0x0,0x0
  %1 = add i64 %a, 1
  ret i64 %1
}

define i64 @sub(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: sub:
; CHECK:       % %bb.0:
; CHECK-NEXT:    sub $231,$231,$232
; CHECK-NEXT:    pop 0x0,0x0
  %1 = sub i64 %a, %b
  ret i64 %1
}

;; TODO: no sub immediate pattern available? Why not: sub $16,$16,0xff
define i64 @subi(i64 %a) nounwind {
; CHECK-LABEL: subi:
; CHECK:       % %bb.0:
; CHECK-NEXT:    neg $16,0x0,0xff
; CHECK-NEXT:    add $231,$231,$16
; CHECK-NEXT:    pop 0x0,0x0
  %1 = sub i64 %a, 255
  ret i64 %1
}
