; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mmix -verify-machineinstrs < %s | FileCheck %s

define i64 @zero() nounwind {
; CHECK-LABEL: zero:
; CHECK:       % %bb.0:
; CHECK-NEXT:    setl $231,0x0
; CHECK-NEXT:    pop 0x0,0x0
  ret i64 0
}

define i64 @pos_ui16() nounwind {
; CHECK-LABEL: pos_ui16:
; CHECK:       % %bb.0:
; CHECK-NEXT:    setl $231,0xffff
; CHECK-NEXT:    pop 0x0,0x0
  ret i64 65535
}

define i64 @pos_i64() nounwind {
; CHECK-LABEL: pos_i64:
; CHECK:       % %bb.0:
; CHECK-NEXT:    seth $231,0x8899
; CHECK-NEXT:    ormh $231,0xaabb
; CHECK-NEXT:    orml $231,0xccdd
; CHECK-NEXT:    orl $231,0xeeff
; CHECK-NEXT:    pop 0x0,0x0
  ret i64 9843086184167632639
}

define i64 @neg_i64() nounwind {
; CHECK-LABEL: neg_i64:
; CHECK:       % %bb.0:
; CHECK-NEXT:    seth $231,0xfedc
; CHECK-NEXT:    ormh $231,0xba98
; CHECK-NEXT:    orml $231,0x7654
; CHECK-NEXT:    orl $231,0x3210
; CHECK-NEXT:    pop 0x0,0x0
  ret i64  -81985529216486896
}
