name: rebase-master

on:
  schedule:
    - cron:  '30 2 * * 6'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: configure git and install things
      run: |
        git config --global user.email "ties@stuij.se"
        git config --global user.name "Ties Stuij"
        sudo pip install ninja psutil
        git clone https://github.com/stuij/mmix-llvm-support.git support
        wget https://github.com/stuij/binutils-gdb/releases/download/binutils-2.16.91-20051206/mmix-objcopy -O support/bin/mmix-objcopy
        chmod +x support/bin/mmix-objcopy
        wget https://github.com/ascherer/mmix/releases/download/2017-09-17/mmix_20170917-2_amd64.deb
        sudo apt install ./mmix_20170917-2_amd64.deb

    - name: unshallow and check branch
      run: |
        git fetch --unshallow --tags
        git branch
        git --no-pager log -n 5 --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit

    - name: add and fetch upstream
      run: |
        git remote add upstream https://github.com/llvm/llvm-project
        git fetch upstream

    - name: rebase
      run: git pull --rebase upstream master

    - name: apply patches, build and test
      run: |
        BASE=$(git merge-base master upstream/master)
        support/bin/check-patches.sh -c $BASE -l 1 . tmp

    - name: push rebase
      run: git push -f

    - name: tag and push tag
      run: |
        printf -v TAG_NAME 'upstream-rebase-%(%Y-%m-%d)T\n' -1
        git tag $TAG_NAME
        git push origin $TAG_NAME
